apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: sample-app-dev
images:
  - name: ghcr.io/eameer/gitops-argo-exercise/sample-app
    newTag: latest  # updated by CI on every push to app/**
patches:
  - path: ingress-patch.yaml
  - path: resources-patch.yaml
