# ClusterSecretStore — ESO reads from a K8s Secret in the 'argocd' namespace.
#
# The source secret (app-source-secrets) is created by the cluster-bootstrap Helm chart
# and lives in the argocd namespace alongside nginx and ArgoCD itself.
# ESO syncs keys from that secret into other namespaces via ExternalSecret objects.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: local-k8s-store
spec:
  provider:
    kubernetes:
      # Namespace where the source secrets live (created by charts/cluster-bootstrap)
      remoteNamespace: argocd
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
